# @author DiZed Team
# @copyright Copyright (c) DiZed Team (https://github.com/di-zed/)
version: '3'

services:

  node18:
    container_name: node18-ysh
    image: node:18.18.0
    command: npm run start
    hostname: docker-node18
    ports:
      - "${SERVER_PORT}:3000"
      - "${SERVER_TLS_PORT}:443"
    volumes:
      - .:/home/app
      - ./volumes/etc/ssl:/etc/ssl/docker:cached
    environment:
      NODE_ENV: ${NODE_ENV}
    working_dir: /home/app
    depends_on:
      - eclipse-mosquitto
      - redis
    networks:
      - internal

  eclipse-mosquitto:
    container_name: eclipse-mosquitto-ysh
    image: eclipse-mosquitto:2.0.18
    hostname: docker-eclipse-mosquitto
    ports:
      - "${MQTT_PORT}:1883"
      - "${MQTT_TLS_PORT}:8883"
      - "${MQTT_WS_PORT}:9001"
      - "${MQTT_WSS_PORT}:8884"
    volumes:
      - eclipse_mosquitto_data:/mosquitto/data
      - ./volumes/etc/mosquitto:/etc/mosquitto
      - ./volumes/mosquitto/config/conf.d:/mosquitto/config/conf.d
      - ./volumes/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./volumes/mosquitto/log:/mosquitto/log:delegated
    networks:
      - internal

  redis:
    container_name: redis-ysh
    image: redis:7.4-rc1-alpine3.20
    command: redis-server /usr/local/etc/redis/redis.conf
    hostname: docker-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./volumes/data:/data:delegated
      - ./volumes/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./volumes/var/run:/var/run:delegated
    networks:
      - internal

volumes:

  eclipse_mosquitto_data:

networks:

  internal:
    driver: bridge